name: "Hello Actions"
description: "Greet someone"
author: "octocat@github.com"

inputs:
  owner:
    description:
      'owner'
    required: true
  version:
    description:
      'version'
    required: true
  branch:
    description:
      'branch'
    required: true

runs:
  using: "docker"
  image: "ArielWeb/Dockerfile"
  args:
  - '-o'
  - ${{ inputs.owner }}
  - '-v'
  - ${{ inputs.version }}
  - '-b'
  - ${{ inputs.branch }}

branding:
  icon: "mic"
  color: "purple"