name: "Hello Actions"
description: "Greet someone"
author: "octocat@github.com"

inputs:
  owner:
    description:
      'owner'
    required: true
  version:
    description:
      'version'
    required: true

runs:
  using: "docker"
  image: "./action-a/ArielWeb/Dockerfile"
  args:
  - '-o'
  - ${{ inputs.owner }}
  - '-v'
  - ${{ inputs.version }}

branding:
  icon: "mic"
  color: "purple"